# default username admin@admin.com password password
services:
  mysql:
    image: mysql:9.2
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - mysql-data:/var/lib/mysql

  bookstack:
    image: solidnerd/bookstack:master
#    image: bookstack:25.07.3
#    build:
#      context: ./
#      dockerfile: Dockerfile
    depends_on:
    - mysql
    environment:
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    # Set the APP_ to the URL of bookstack without without a trailing slash,
    # but including any port numbers. For example, one of:
    # APP_URL=https://example.com
    # APP_URL=http://localhost:8080
    # APP_URL=https://wiki.example.com:8443
    - APP_URL=http://localhost:8080
    # APP_KEY is used for encryption where needed, so needs to be persisted to
    # preserve decryption abilities.
    # Can run `php artisan key:generate` to generate a key
    - APP_KEY=SomeRandomStringWith32Characters
    volumes:
    - uploads:/var/www/bookstack/public/uploads
    - storage-uploads:/var/www/bookstack/storage/uploads
    ports:
    - "8080:8080"

volumes:
 mysql-data:
 uploads:
 storage-uploads:
